### ISSUE TITLE
Wire enhancements

### ISSUE THREAD

**Issue by simlhawk** [Creysys/ThermalScience#1]
Currently, the wire production on the lower tiers is fairly quick, It'd be nice to have good motivation to move up in the tiers. Slowing down the production speed would help with that in the lower tiers.

Also, could there be a config to add custom wires? Perhaps certain tiers can only make different tiers of wires. I've started using copper wires for recipes in my modpack, and it would be nice to have different tiers of wires, such as gold wires and enderium wires.

**Comment by Creysys** [comment]
Both things that you mentioned were actually on my list even before the teleporter (more wires, machine balancing) so i dont really know why i did the teleporter first :)

Anyways, i hope i can get both things to work in the next version which should be up later this day or tomorrow we'll see.

**Comment by Creysys** [comment]
Version 1.1b is now released tell me what you think about the new wires :)

**Comment by simlhawk** [comment]
I like them. That's going to be awesome, thank you.

Not sure I should create a new ticket for this, but could you add a section to your config for custom blocks that can be compressed in the portable compressor? Currently, I have Extra Utilities in my pack, which adds "compressed cobble" amongst other things. It would be nice if it could compress things like that :)

**Comment by Creysys** [comment]
Well it already can it should at least ;)
