### ISSUE TITLE
An extruder type machine

### ISSUE THREAD

**Issue by chanzie** [Creysys/ThermalScience#2]
a machine like ic2s extruder where you can put the rubber logs in from mfr and get a boosted rubber return from them, just a suggestion

**Comment by Creysys** [comment]
I was thinking something like an extractor if that is what you mean.

You could put in some rubber logs and get like 2 raw rubber from it.

Or i could make it a new recipe in the centrifuge :S

I dont know you da man, centrifuge recipe or new machine?

**Comment by chanzie** [comment]
new machine would be my take on it

**Comment by Creysys** [comment]
alright
