### ISSUE TITLE
java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by Tsyklop** [Creysys/ThermalScience#6]
Crash. Error: http://pastebin.com/hNJfRckn

ThermalExpansion and CoFHCore installed.

**Comment by Creysys** [comment]
It seems like it isnt compatible with your ExtraUtilities version.

Id recommend you to play without the mod since there will not be an update any time soon due to school n stuff.

Im sorry man

**Comment by Tsyklop** [comment]
thx. Ok.
